rabbitmq:
    url: 'amqp://guest:guest@localhost:5672/%2F?connection_attempts=3&heartbeat_interval=3600'
    consumers:
      - name: 'tasking.request.from.controller'
        exchange: 'incoming'
        exchange_type: 'direct'
        queue: 'tasking.request.from.controller'
        routing_key: 'tasking.request.from.controller'
      - name: 'tasking.respone.from.handler'
        exchange: 'incoming'
        exchange_type: 'direct'
        queue: 'tasking.respone.from.handler'
        routing_key: 'tasking.respone.from.handler'
      - name: 'connect.from.handler'
        exchange: 'incoming'
        exchange_type: 'direct'
        queue: 'connect.from.handler'
        routing_key: 'connect.from.handler'
    publishers:
      - name: 'tasking.requst.to.handler'
        exchange: 'outgoing'
        exchange_type: 'fanout'
        queue: 'tasking.requst.to.handler'
        routing_key: 'tasking.requst.to.handler'
      - name: 'tasking.response.to.controller'
        exchange: 'outgoing'
        exchange_type: 'fanout'
        queue: 'tasking.response.to.controller'
        routing_key: 'tasking.response.to.controller'
      - name: 'connect.to.controller'
        exchange: 'outgoing'
        exchange_type: 'fanout'
        queue: 'connect.to.controller'
        routing_key: 'connect.to.controller'
